export default {
    FETCH_RECIPES_START: "FETCH_RECIPES_START",
    FETCH_RECIPES_SUCCESS: "FETCH_RECIPES_SUCCESS",
    FETCH_RECIPES_ERROR: "FETCH_RECIPES_ERROR",
    RECIPE_ADD_START: "RECIPE_ADD_START",
    RECIPE_ADD_SUCCESS: "RECIPE_ADD_SUCCESS",
    RECIPE_ADD_ERROR: "RECIPE_ADD_ERROR"
}