export default {
    FETCH_RECIPES_START: "FETCH_RECIPES_START",
    FETCH_RECIPES_SUCCESS: "FETCH_RECIPES_SUCCESS",
    FETCH_RECIPES_ERROR: "FETCH_RECIPES_ERROR",
    FETCH_ONE_RECIPE_START: "FETCH_ONE_RECIPE_START",
    FETCH_ONE_RECIPE_SUCCESS: "FETCH_ONE_RECIPE_SUCCESS",
    FETCH_ONE_RECIPE_ERROR: "FETCH_ONE_RECIPE_ERROR",
    RECIPE_ADD_START: "RECIPE_ADD_START",
    RECIPE_ADD_SUCCESS: "RECIPE_ADD_SUCCESS",
    RECIPE_ADD_ERROR: "RECIPE_ADD_ERROR",
    RECIPE_EDIT_START: "RECIPE_EDIT_START",
    RECIPE_EDIT_SUCCESS: "RECIPE_EDIT_SUCCESS",
    RECIPE_EDIT_ERROR: "RECIPE_EDIT_ERROR"
}